# MCP Server Configuration
# Defines available MCP servers and their capabilities for persona enhancement

servers:
  sequential:
    url: "mcp://sequential.ai/strategic-analysis"
    capabilities: 
      - "systematic_analysis"
      - "framework_application" 
      - "strategic_planning"
      - "organizational_analysis"
      - "decision_frameworks"
    personas: 
      - "diego"
      - "camille"
    timeout: 10
    max_retries: 3
    description: "Systematic strategic analysis and organizational frameworks"
    
  context7:
    url: "mcp://context7.ai/frameworks"
    capabilities:
      - "pattern_access"
      - "methodology_lookup"
      - "best_practices"
      - "architectural_patterns"
      - "design_frameworks"
      - "leadership_frameworks"
    personas:
      - "martin"
      - "rachel"
      - "camille"
    timeout: 8
    max_retries: 3
    description: "Access to proven patterns, methodologies, and frameworks"
    
  magic:
    url: "mcp://magic.dev/visualization"
    capabilities:
      - "diagram_generation"
      - "presentation_creation"
      - "visual_storytelling"
      - "data_visualization"
    personas:
      - "rachel"
      - "alvaro"
    timeout: 12
    max_retries: 2
    description: "Professional visual generation and presentation creation"

# Enhancement trigger thresholds
enhancement_thresholds:
  # Systematic analysis threshold (0.0-1.0)
  # Higher values = more selective about when to use MCP enhancement
  systematic_analysis: 0.7
  
  # Framework lookup threshold
  framework_lookup: 0.6
  
  # Visual generation threshold  
  visual_generation: 0.8
  
  # Minimum complexity score for any MCP enhancement
  minimum_complexity: 0.5

# Persona-specific enhancement preferences
persona_preferences:
  diego:
    primary_server: "sequential"
    fallback_servers: ["context7"]
    enhancement_types: ["systematic_analysis", "strategic_planning"]
    auto_enhance_keywords: 
      - "strategic planning"
      - "organizational design"  
      - "team structure"
      - "quarterly planning"
      - "crisis management"
      - "stakeholder alignment"
    
  martin:
    primary_server: "context7"
    fallback_servers: []
    enhancement_types: ["pattern_access", "architectural_patterns"]
    auto_enhance_keywords:
      - "architecture"
      - "technical debt"
      - "system design"
      - "platform patterns"
      - "evolutionary design"
      - "refactoring strategy"
    
  rachel:
    primary_server: "context7"
    fallback_servers: ["magic"]
    enhancement_types: ["design_frameworks", "visual_storytelling"]
    auto_enhance_keywords:
      - "design system"
      - "user experience"
      - "cross-team alignment"
      - "design maturity"
      - "scaling design"
      - "visual communication"
    
  camille:
    primary_server: "sequential"
    fallback_servers: ["context7"]
    enhancement_types: ["systematic_analysis", "leadership_frameworks"]
    auto_enhance_keywords:
      - "organizational health"
      - "leadership development"
      - "team scaling"
      - "cultural change"
      - "strategic alignment"
      - "executive decision"
    
  alvaro:
    primary_server: "magic"
    fallback_servers: ["sequential"]
    enhancement_types: ["visual_storytelling", "systematic_analysis"]
    auto_enhance_keywords:
      - "business case"
      - "roi analysis"
      - "market positioning"
      - "competitive analysis"
      - "presentation"
      - "stakeholder communication"

# Caching configuration
cache_settings:
  # TTL for different types of responses (in seconds)
  systematic_analysis: 1800    # 30 minutes
  framework_lookup: 3600       # 1 hour  
  pattern_access: 7200         # 2 hours
  visual_generation: 300       # 5 minutes (more dynamic)
  
  # Maximum cache size (number of entries)
  max_cache_size: 1000
  
  # Cache cleanup interval (seconds)
  cleanup_interval: 300

# Circuit breaker configuration
circuit_breaker:
  # Number of consecutive failures before opening circuit
  failure_threshold: 5
  
  # Time to wait before trying to close circuit (seconds)
  recovery_timeout: 60
  
  # Number of successful requests needed to close circuit
  success_threshold: 3

# Performance monitoring
monitoring:
  # Log slow requests (milliseconds)
  slow_request_threshold: 5000
  
  # Log performance metrics interval (seconds)
  metrics_interval: 300
  
  # Track these metrics
  tracked_metrics:
    - "request_count"
    - "response_time"
    - "error_rate"
    - "cache_hit_rate"
    - "circuit_breaker_state"

# Development and testing
development:
  # Mock servers for testing when real servers unavailable
  use_mock_servers: false
  
  # Mock server responses directory
  mock_responses_dir: ".claudedirector/tests/fixtures/mock_mcp_responses"
  
  # Enable debug logging for MCP operations
  debug_logging: false
  
  # Simulate server delays for testing (milliseconds)
  simulated_delay: 0
