# P0 Features Configuration - Production Environment
# Martin's production-optimized settings for maximum reliability

environment: production
debug_mode: false

# Stricter performance requirements in production
decision_detection:
  accuracy_threshold: 0.90    # Higher accuracy requirement
  confidence_threshold: 0.70  # Higher confidence requirement

health_prediction:
  accuracy_threshold: 0.85    # Higher accuracy requirement

# Enhanced monitoring in production
monitoring:
  enable_performance_tracking: true
  enable_accuracy_tracking: true
  metrics_retention_days: 90  # Longer retention
  alert_on_sla_violation: true
  performance_sample_rate: 1.0  # Full sampling

# Stricter performance thresholds
performance:
  max_inference_time_ms: 150  # Slightly tighter SLA
  min_accuracy: 0.90          # Higher accuracy requirement
  max_memory_usage_mb: 100    # Tighter memory constraint
  max_error_rate: 0.02        # Very low error tolerance

# Production database optimizations
database:
  connection_timeout: 60      # Longer timeout for reliability
  query_timeout: 30          # Longer query timeout
  max_connections: 20        # More connections for load
