# ClaudeDirector User Identity Configuration
# Centralizes user information for personalized system messages and documentation

# User Identity - TEMPLATE FILE
# Copy this to user_identity.yaml and customize with your information
user:
  # Primary name for system messages and documentation
  name: "User"

  # Preferred work name (used in professional contexts)  
  work_name: ""

  # Full name (used in formal documentation)
  full_name: ""

  # Role/title for context
  role: ""

  # Organization for context
  organization: ""

# Usage Context
# When to use which name:
# - name: Default for all system messages ("User's requirement")
# - work_name: Professional contexts if specified, falls back to name
# - full_name: Formal documentation if specified, falls back to name
# - If all empty, system uses "User" as default

# P0 Enforcement Attribution
# The P0 test enforcement system will use the configured name to properly
# attribute requirements instead of hardcoding names.

# Example Configuration:
# user:
#   name: "Your Name"
#   work_name: "Your Work Name"
#   full_name: "Your Full Name"
#   role: "Your Role"
#   organization: "Your Organization"

# Configuration Priority:
# 1. Environment variables (CLAUDEDIRECTOR_USER_NAME, etc.)
# 2. This configuration file
# 3. Default "User"

# Security Note:
# This file may contain personal information. Consider adding to .gitignore
# for shared repositories or use environment variables for sensitive deployments.
