# Pre-commit configuration for ClaudeDirector
repos:
  # Basic code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=88]
        files: ^lib/claudedirector/.*\.py$

  # CRITICAL FILE PROTECTION (MUST RUN FIRST)
  - repo: local
    hooks:
      - id: readme-protection
        name: 🛡️ README.md PROTECTION SYSTEM
        entry: .claudedirector/git-hooks/readme-protection.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
        verbose: true

  # CRITICAL SECURITY ENFORCEMENT
  - repo: local
    hooks:
      - id: enhanced-security-scanner
        name: 🛡️ ENHANCED SECURITY SCAN
        entry: python3 .claudedirector/dev-tools/security/enhanced_security_scanner.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
        verbose: true
      - id: stakeholder-name-scanner
        name: 🚨 STAKEHOLDER INTELLIGENCE SCAN
        entry: python3 .claudedirector/dev-tools/security/stakeholder_name_scanner.py --staged
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
        verbose: true

  # MANDATORY TEST VALIDATION (BLOCKS ALL COMMITS IF TESTS FAIL)
  - repo: local
    hooks:
      - id: mandatory-test-validation
        name: 🛡️ MANDATORY TEST VALIDATION
        entry: python3 .claudedirector/dev-tools/testing/mandatory_test_validator.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
        verbose: true

  # Architectural governance
  - repo: local
    hooks:
      - id: solid-principle-validator
        name: SOLID Principle Validation
        entry: python .claudedirector/dev-tools/architecture/solid_validator.py
        language: python
        files: ^lib/claudedirector/(p0_features|p1_features)/.*\.py$
        pass_filenames: true

      # P1 Feature Testing
      - id: p1-unit-tests
        name: P1 Unit Tests
        entry: python .claudedirector/dev-tools/testing/run_p1_unit_tests.py
        language: python
        files: ^(lib/claudedirector/p1_features/.*\.py|tests/p1_features/unit/.*\.py)$
        pass_filenames: false

      - id: p1-test-coverage
        name: P1 Test Coverage Check
        entry: python .claudedirector/dev-tools/testing/check_p1_coverage.py
        language: python
        files: ^lib/claudedirector/p1_features/.*\.py$
        pass_filenames: false
