alerts:
  executive_alerts:
    enabled: true
    frequency: weekly
    thresholds:
      cross_team_velocity_decline:
        severity: critical
        threshold: -0.1
      design_system_adoption_drop:
        severity: high
        threshold: -0.05
      developer_satisfaction_drop:
        severity: medium
        threshold: -0.3
business_value:
  value_drivers:
    cross_team_velocity:
      annual_value_per_percent: 20000
      enabled: true
      measurement_method: coordination_and_delivery
    design_consistency:
      annual_value_per_percent: 8000
      enabled: true
      measurement_method: brand_and_ux_metrics
    developer_productivity:
      annual_value_per_percent: 15000
      enabled: true
      measurement_method: velocity_and_satisfaction
    platform_adoption:
      annual_value_per_percent: 12000
      enabled: true
      measurement_method: team_onboarding_and_usage
dashboard:
  custom_widgets:
  - enabled: true
    position: top_left
    refresh_rate: hourly
    type: design_system_health
  - enabled: true
    position: top_right
    refresh_rate: daily
    type: platform_adoption_trends
  - enabled: true
    position: middle_left
    refresh_rate: daily
    type: cross_team_dependencies
  - enabled: true
    position: middle_right
    refresh_rate: weekly
    type: investment_roi_tracking
  - enabled: true
    position: bottom_full
    refresh_rate: daily
    type: developer_experience_metrics
  layout: platform_director
debug_mode: true
director_profile:
  custom_profile:
    primary_focus: Web platform, design system, internationalization, developer experience
    role_title: Director of Engineering - UI Foundation
    strategic_priorities:
    - Platform scalability and developer experience
    - Design system adoption and consistency
    - International expansion support
    - Cross-team developer velocity
    success_metrics:
    - design_system_leverage
    - platform_adoption
    - developer_experience
  profile_type: custom
environment: development
integrations:
  analytics:
    datadog:
      api_key_env: DATADOG_API_KEY
      enabled: false
      tracking_metrics:
      - platform_performance
      - user_experience
  design_tools:
    figma:
      api_key_env: FIGMA_API_KEY
      enabled: false
      tracking_metrics:
      - component_usage
      - design_consistency
    sketch:
      api_key_env: SKETCH_API_KEY
      enabled: false
      tracking_metrics:
      - component_usage
  development_tools:
    github:
      api_key_env: GITHUB_API_KEY
      enabled: true
      tracking_metrics:
      - component_adoption
      - code_consistency
    jira:
      api_key_env: JIRA_API_KEY
      enabled: true
      tracking_metrics:
      - feature_delivery
      - cross_team_coordination
organizational_intelligence:
  dependency_mapping:
    enabled: true
    tracking_domains:
      downstream_consumers:
      - consumes:
        - ui_components
        - platform_services
        - development_tools
        satisfaction_weight: 0.5
        team: Product Teams
      - consumes:
        - design_system
        - brand_consistency
        - performance_optimization
        satisfaction_weight: 0.3
        team: Marketing Technology
      - consumes:
        - shared_components
        - cross_platform_patterns
        - accessibility_guidelines
        satisfaction_weight: 0.2
        team: Mobile Teams
      upstream_dependencies:
      - impact_weight: 0.4
        outputs:
        - component_library
        - design_tokens
        - accessibility_standards
        team: Design Systems Team
      - impact_weight: 0.3
        outputs:
        - deployment_pipeline
        - monitoring_tools
        - performance_metrics
        team: Platform Infrastructure
      - impact_weight: 0.3
        outputs:
        - localization_framework
        - content_management
        - cultural_adaptation
        team: Internationalization
  investment_intelligence:
    enabled: true
    investment_categories:
      cross_team_tooling:
        enabled: true
        measurement_period_months: 9
        priority_weight: 0.1
        roi_calculation_method: coordination_efficiency
        success_criteria:
        - metric: cross_team_communication_efficiency
          target: 0.3
          weight: 1.0
      design_system_enhancement:
        enabled: true
        measurement_period_months: 6
        priority_weight: 0.35
        roi_calculation_method: developer_velocity_improvement
        success_criteria:
        - metric: component_adoption_rate
          target: 0.85
          weight: 0.4
        - metric: development_velocity_improvement
          target: 0.25
          weight: 0.6
      developer_experience:
        enabled: true
        measurement_period_months: 3
        priority_weight: 0.25
        roi_calculation_method: productivity_and_satisfaction
        success_criteria:
        - metric: developer_satisfaction
          target: 4.5
          weight: 0.6
        - metric: onboarding_efficiency
          target: 0.6
          weight: 0.4
      platform_infrastructure:
        enabled: true
        measurement_period_months: 12
        priority_weight: 0.3
        roi_calculation_method: operational_efficiency
        success_criteria:
        - metric: deployment_frequency
          target: 2.0
          weight: 0.5
        - metric: mean_time_to_recovery
          target: 0.5
          weight: 0.5
  velocity_tracking:
    enabled: true
    measurement_domains:
      api_service_efficiency:
        enabled: false
        metrics:
        - api_response_times
        - service_dependency_health
        - integration_complexity
        targets:
          dependency_health: 0.95
          integration_score: 0.8
          response_time_ms: 200
        weight: 0.4
      design_system_leverage:
        enabled: true
        metrics:
        - component_usage_consistency
        - design_debt_reduction
        - cross_team_design_velocity
        targets:
          consistency_score: 0.85
          debt_reduction_monthly: 0.15
          velocity_improvement: 0.2
        weight: 0.35
      feature_delivery_impact:
        enabled: false
        metrics:
        - cross_team_delivery_velocity
        - feature_adoption_rates
        - user_experience_consistency
        targets:
          adoption_rate: 0.7
          ux_consistency: 0.9
          velocity_improvement: 0.25
        weight: 0.4
      knowledge_sharing:
        enabled: false
        metrics:
        - cross_team_learning_index
        - best_practice_adoption
        - institutional_knowledge_retention
        targets:
          knowledge_retention: 0.85
          learning_index: 0.75
          practice_adoption: 0.6
        weight: 0.3
      platform_adoption:
        enabled: true
        metrics:
        - adoption_rate_percentage
        - developer_satisfaction_score
        - time_to_onboard_new_teams
        targets:
          adoption_rate: 0.8
          onboard_time_days: 3
          satisfaction_score: 4.2
        weight: 0.3
preset_profiles:
  backend_director:
    dashboard_layout: services_focused
    focus_areas:
    - api_service_efficiency
    - system_reliability
    - cross_team_coordination
    key_metrics:
    - api_performance
    - service_uptime
    - integration_health
  platform_director:
    dashboard_layout: platform_focused
    focus_areas:
    - platform_adoption
    - design_system_leverage
    - developer_experience
    key_metrics:
    - adoption_rate
    - developer_satisfaction
    - design_consistency
  product_director:
    dashboard_layout: product_focused
    focus_areas:
    - feature_delivery_impact
    - user_experience
    - market_responsiveness
    key_metrics:
    - delivery_velocity
    - user_satisfaction
    - feature_adoption
