# P1 Organizational Leverage Intelligence - Configuration-Driven Framework
# Tailorable for any director role while maintaining broad applicability

environment: development
debug_mode: true

# Director Profile Configuration - User Customizable
director_profile:
  # User can select or customize their profile
  profile_type: "platform_director"  # platform_director, backend_director, product_director, custom

  # Custom profile definition (overrides preset if profile_type: "custom")
  custom_profile:
    role_title: "Director of Engineering - UI Foundation"
    primary_focus: "Web platform, design system, internationalization, ui-service-shell"
    strategic_priorities:
      - "Platform scalability and developer experience"
      - "Design system adoption and consistency"
      - "International expansion support"
      - "Cross-team developer velocity"
    success_metrics:
      - "Platform adoption rates"
      - "Developer satisfaction scores"
      - "Design system component usage"
      - "Time-to-market improvements"

# Organizational Intelligence Configuration
organizational_intelligence:
  # Cross-Team Velocity Intelligence
  velocity_tracking:
    enabled: true
    measurement_domains:
      # User can enable/configure domains relevant to their context
      platform_adoption:
        enabled: true
        weight: 0.3  # Relative importance for this director
        metrics:
          - adoption_rate_percentage
          - developer_satisfaction_score
          - time_to_onboard_new_teams
        targets:
          adoption_rate: 0.80
          satisfaction_score: 4.2
          onboard_time_days: 3

      design_system_leverage:
        enabled: true  # You would enable this, backend director might disable
        weight: 0.25
        metrics:
          - component_usage_consistency
          - design_debt_reduction
          - cross_team_design_velocity
        targets:
          consistency_score: 0.85
          debt_reduction_monthly: 0.15
          velocity_improvement: 0.20

      api_service_efficiency:
        enabled: false  # You might disable, backend director would enable
        weight: 0.0
        metrics:
          - api_response_times
          - service_dependency_health
          - integration_complexity
        targets:
          response_time_ms: 200
          dependency_health: 0.95
          integration_score: 0.80

      feature_delivery_impact:
        enabled: true
        weight: 0.25
        metrics:
          - cross_team_delivery_velocity
          - feature_adoption_rates
          - user_experience_consistency
        targets:
          velocity_improvement: 0.25
          adoption_rate: 0.70
          ux_consistency: 0.90

      knowledge_sharing:
        enabled: true
        weight: 0.20
        metrics:
          - cross_team_learning_index
          - best_practice_adoption
          - institutional_knowledge_retention
        targets:
          learning_index: 0.75
          practice_adoption: 0.60
          knowledge_retention: 0.85

  # Cross-Team Dependency Intelligence
  dependency_mapping:
    enabled: true
    tracking_domains:
      # Configurable based on your organizational structure
      upstream_dependencies:
        - team: "Design Systems Team"
          outputs: ["component_library", "design_tokens", "accessibility_standards"]
          impact_weight: 0.4
        - team: "Platform Infrastructure"
          outputs: ["deployment_pipeline", "monitoring_tools", "performance_metrics"]
          impact_weight: 0.3
        - team: "Internationalization"
          outputs: ["localization_framework", "content_management", "cultural_adaptation"]
          impact_weight: 0.3

      downstream_consumers:
        - team: "Product Teams"
          consumes: ["ui_components", "platform_services", "development_tools"]
          satisfaction_weight: 0.5
        - team: "Marketing Technology"
          consumes: ["design_system", "brand_consistency", "performance_optimization"]
          satisfaction_weight: 0.3
        - team: "Mobile Teams"
          consumes: ["shared_components", "cross_platform_patterns", "accessibility_guidelines"]
          satisfaction_weight: 0.2

  # Investment ROI Intelligence
  investment_intelligence:
    enabled: true
    investment_categories:
      # Configurable investment areas relevant to your context
      design_system_enhancement:
        enabled: true
        priority_weight: 0.35
        roi_calculation_method: "developer_velocity_improvement"
        measurement_period_months: 6
        success_criteria:
          - metric: "component_adoption_rate"
            target: 0.85
            weight: 0.4
          - metric: "development_velocity_improvement"
            target: 0.25
            weight: 0.6

      platform_infrastructure:
        enabled: true
        priority_weight: 0.30
        roi_calculation_method: "operational_efficiency"
        measurement_period_months: 12
        success_criteria:
          - metric: "deployment_frequency"
            target: 2.0  # 2x improvement
            weight: 0.5
          - metric: "mean_time_to_recovery"
            target: 0.5  # 50% reduction
            weight: 0.5

      developer_experience:
        enabled: true
        priority_weight: 0.25
        roi_calculation_method: "productivity_and_satisfaction"
        measurement_period_months: 3
        success_criteria:
          - metric: "developer_satisfaction"
            target: 4.5
            weight: 0.6
          - metric: "onboarding_efficiency"
            target: 0.6  # 40% time reduction
            weight: 0.4

      cross_team_tooling:
        enabled: true
        priority_weight: 0.10
        roi_calculation_method: "coordination_efficiency"
        measurement_period_months: 9
        success_criteria:
          - metric: "cross_team_communication_efficiency"
            target: 0.3  # 30% improvement
            weight: 1.0

# Business Value Calculation Framework
business_value:
  # Configurable value drivers specific to your context
  value_drivers:
    developer_productivity:
      enabled: true
      annual_value_per_percent: 15000  # $15K per 1% productivity improvement
      measurement_method: "velocity_and_satisfaction"

    design_consistency:
      enabled: true
      annual_value_per_percent: 8000   # $8K per 1% consistency improvement
      measurement_method: "brand_and_ux_metrics"

    platform_adoption:
      enabled: true
      annual_value_per_percent: 12000  # $12K per 1% adoption improvement
      measurement_method: "team_onboarding_and_usage"

    cross_team_velocity:
      enabled: true
      annual_value_per_percent: 20000  # $20K per 1% cross-team velocity improvement
      measurement_method: "coordination_and_delivery"

# Alerting and Reporting Configuration
alerts:
  executive_alerts:
    enabled: true
    frequency: "weekly"
    thresholds:
      # Configurable based on your strategic priorities
      design_system_adoption_drop:
        threshold: -0.05  # 5% drop triggers alert
        severity: "high"

      cross_team_velocity_decline:
        threshold: -0.10  # 10% decline triggers alert
        severity: "critical"

      developer_satisfaction_drop:
        threshold: -0.3   # 0.3 point drop triggers alert
        severity: "medium"

# Dashboard Configuration
dashboard:
  layout: "platform_director"  # Pre-configured layouts available

  custom_widgets:
    # You can customize which widgets appear in your dashboard
    - type: "design_system_health"
      position: "top_left"
      enabled: true
      refresh_rate: "hourly"

    - type: "platform_adoption_trends"
      position: "top_right"
      enabled: true
      refresh_rate: "daily"

    - type: "cross_team_dependencies"
      position: "middle_left"
      enabled: true
      refresh_rate: "daily"

    - type: "investment_roi_tracking"
      position: "middle_right"
      enabled: true
      refresh_rate: "weekly"

    - type: "developer_experience_metrics"
      position: "bottom_full"
      enabled: true
      refresh_rate: "daily"

# Integration Points (Optional - User Configurable)
integrations:
  design_tools:
    figma:
      enabled: false  # You could enable this
      api_key_env: "FIGMA_API_KEY"
      tracking_metrics: ["component_usage", "design_consistency"]

    sketch:
      enabled: false
      api_key_env: "SKETCH_API_KEY"
      tracking_metrics: ["component_usage"]

  development_tools:
    github:
      enabled: true
      api_key_env: "GITHUB_API_KEY"
      tracking_metrics: ["component_adoption", "code_consistency"]

    jira:
      enabled: true
      api_key_env: "JIRA_API_KEY"
      tracking_metrics: ["feature_delivery", "cross_team_coordination"]

  analytics:
    datadog:
      enabled: false
      api_key_env: "DATADOG_API_KEY"
      tracking_metrics: ["platform_performance", "user_experience"]

# Preset Configurations for Different Director Types
preset_profiles:
  platform_director:
    focus_areas: ["platform_adoption", "design_system_leverage", "developer_experience"]
    key_metrics: ["adoption_rate", "developer_satisfaction", "design_consistency"]
    dashboard_layout: "platform_focused"

  backend_director:
    focus_areas: ["api_service_efficiency", "system_reliability", "cross_team_coordination"]
    key_metrics: ["api_performance", "service_uptime", "integration_health"]
    dashboard_layout: "services_focused"

  product_director:
    focus_areas: ["feature_delivery_impact", "user_experience", "market_responsiveness"]
    key_metrics: ["delivery_velocity", "user_satisfaction", "feature_adoption"]
    dashboard_layout: "product_focused"
