# P1.1 Visualization Configuration
# Following DRY principles - all hard-coded values extracted to config

# Sample Data Configuration
sample_data:
  # Current metrics for demonstration
  metrics:
    component_usage_consistency: 0.78
    design_debt_reduction: 0.12
    cross_team_design_velocity: 0.22
    adoption_rate_percentage: 0.75
    developer_satisfaction_score: 4.3
    time_to_onboard_new_teams: 2.8
    api_response_times: 180
    service_dependency_health: 0.95

  # Domain performance simulation
  domain_performance:
    design_domains:
      current: 0.78
      default_target: 0.8
    platform_domains:
      current: 0.75
      default_target: 0.8
    api_domains:
      current: 0.85
      default_target: 0.8
    other_domains:
      current: 0.70
      default_target: 0.8

  # Trend data (8-week simulation)
  trends:
    design_system_leverage: [0.65, 0.68, 0.71, 0.73, 0.75, 0.77, 0.78, 0.78]
    platform_adoption: [0.68, 0.70, 0.71, 0.72, 0.73, 0.74, 0.75, 0.75]
    api_service_efficiency: [0.80, 0.82, 0.83, 0.84, 0.85, 0.85, 0.85, 0.85]

  # Investment ROI multipliers
  investment_multipliers:
    design_system_enhancement: 1.25
    platform_infrastructure: 1.18
    developer_experience: 1.30
    cross_team_tooling: 1.15
    default: 1.20

  # Investment base amount
  investment_base: 50000

  # Minimum demo impact score
  minimum_impact_score: 0.65

# Design System Configuration
design_system:
  # Performance score thresholds
  performance_thresholds:
    excellent: 0.95
    good: 0.8
    moderate: 0.6
    poor: 0.0

  # Threshold names for configuration-driven lookup
  threshold_names:
    excellent: "excellent"
    good: "good"
    moderate: "moderate"
    poor: "poor"

  # Shadow opacity values
  shadow_opacities:
    sm: 0.05
    md: 0.1
    lg: 0.1
    xl: 0.1

# ROI Status Configuration
roi_status:
  thresholds:
    excellent: 20
    good: 10
    moderate: 0
  labels:
    excellent: "Excellent"
    good: "Good"
    moderate: "Moderate"
    poor: "Poor"

# Default values to avoid hard-coding
defaults:
  target_fallback: 0.0
  division_by_zero_fallback: 0.0

# Threshold level keys to avoid hard-coding
threshold_keys:
  excellent_key: "excellent"
  good_key: "good"
  moderate_key: "moderate"
  poor_key: "poor"
