name: P0 Mandatory Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  p0-setup-tests:
    name: P0 Setup Feature Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-xvfb structlog

    - name: Make claudedirector executable
      run: |
        chmod +x bin/claudedirector

    - name: Run P0 Setup Feature Tests
      run: |
        python .claudedirector/tests/regression/business_critical/test_setup_p0.py
      timeout-minutes: 5

    - name: Run P0 Setup Regression Protection Tests
      run: |
        python -m unittest .claudedirector.tests.regression.business_critical.test_setup_p0.TestSetupP0RegressionProtection -v
      timeout-minutes: 3

    - name: Verify P0 test integration
      run: |
        python .claudedirector/tests/p0_enforcement/run_mandatory_p0_tests.py | grep -E "(Setup Feature P0|Setup Regression Protection P0)"
      timeout-minutes: 5

  p0-enforcement-validation:
    name: P0 Complete Test Suite
    runs-on: ubuntu-latest
    needs: p0-setup-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest structlog

    - name: Make claudedirector executable
      run: |
        chmod +x bin/claudedirector

    - name: Run Complete P0 Test Suite
      run: |
        python .claudedirector/tests/p0_enforcement/run_mandatory_p0_tests.py
      timeout-minutes: 15

    - name: Upload P0 test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: p0-test-results
        path: .claudedirector/tests/p0_enforcement/results/
        retention-days: 30

  setup-workflow-validation:
    name: Setup Workflow End-to-End Test
    runs-on: ubuntu-latest
    needs: p0-setup-tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install structlog

    - name: Make claudedirector executable
      run: |
        chmod +x bin/claudedirector

    - name: Test setup status command
      run: |
        ./bin/claudedirector status
      timeout-minutes: 2

    - name: Test setup help functionality
      run: |
        ./bin/claudedirector setup --help
        ./bin/claudedirector --help
      timeout-minutes: 1

    - name: Test setup component verification
      run: |
        ./bin/claudedirector setup --verify || echo "Verification completed (may show issues in CI environment)"
      timeout-minutes: 3

    - name: Validate setup directory structure
      run: |
        test -d .claudedirector
        test -d .claudedirector/lib
        test -d .claudedirector/tools
        test -d .claudedirector/tools/setup
        test -f .claudedirector/tools/setup/setup_meeting_intelligence.py
        test -f .claudedirector/tools/setup/setup_smart_git.py
        test -f .claudedirector/tools/setup/setup_stakeholder_management.py
        test -f .claudedirector/tools/setup/setup_task_tracking.py
      timeout-minutes: 1
